### ISSUE TITLE
Fix the endgame mode

### ISSUE THREAD

**Issue by jlouis** [jlouis/etorrent#100]
Klaars recent patch behemoth does not yet handle endgame. It should before the next release.

**Comment by ghost** [comment]
I think we pretty much agreed on a solution to this on IRC.

## Not going into chunk_mgr

The chunk_mgr would have to also maintain a mapping between requests and peer processes. Since we don't already maintain that mapping it would add unnecessary
complexity to that process to handle endgame there. 

## Endgame lifetime

We are only in endgame mode during a limited time at the end of a torrent. We only need the mapping from requests and processes during this time.

## Endgame coordinator

The plan is to add an endgame coordinator to the torrent supervisor. This process will be
responsible for maintaining this mapping and synchronizing the endgame.

## Responsibilities during endgame

### Peer process

The peer_control process is responsible for reporting requests that it aquired from the chunk_mgr server to the endgame coordinator

If the peer_control process cannot aquire a request from the chunk_mgr process it must
aquire one from the endgame coordinator.

### Chunk server

The chunk_mgr server is responsible for telling the peer if it was the first peer to mark a request as fetched if we are in endgame mode. This ensures that two peer processes receiving a chunk at the same time knows which one is responsible for sending out cancellations of the request.

### Endgame coordinator

The endgame coordinator is responsible for maintaining a set of open requests and a mapping between processes and requests during endgame mode. This ensures that a peer receiving a chunk knows which peers it has to tell.

**Comment by jlouis** [comment]
I believe this one has been implemented. If anything is wrong, it better crop up in a separate bug report.
