### ISSUE TITLE
Trying to load a .png as a .torrent file crashes etorrent completely

### ISSUE THREAD

**Issue by hce** [jlouis/etorrent#68]
If you save this png: http://torrents.freebsd.org:8080/files/images/download.png as a .torrent file in etorrent's spool directory, etorrent crashes completely.

**Comment by edwardw** [comment]
Reproduced the bug. And it is quite easy to spot etorrent_io_sup:init/1 fails because of:
    Torrent   = etorrent_bcoding:parse_file(FullPath),
chokes. And it causes a bunch of other Erlang processes fail such as etorrent_io, file_server_sup, etc. Thus the crash.

I just wonder what is the Erlang's way to handle this. Let it crash seems not very practical here.

And by the way, I'm planning to contribute to eTorrent project.

**Comment by jlouis** [comment]
I think the trick is to handle the problem by catching the wrong parse in some way in the parser and then return {error, parse} or something. Then we can case-handle this. I'd argue that the place to check and try to parse the torrent should be in `etorrent_ctl` as this is the right place to try a decode. If the parse is successful it is better to propagate the parsed term rather than let each process do a parse themselves. If it fails, it is probably better to log this and then otherwise ignore the file on disk.

You may also need to fix an error if we try to stop a nonexisting torrent - but that will come with test, I think.

**Comment by edwardw** [comment]
Just send you a pull request for the fix.

I do change spec of both etorrent_bcoding:decode/1 and etorrent_bcoding:parse_file/1 to return {error, Reason}. But I still let individual process to parse torrent file themselves. The thing is that torrent file name is too deeply embedded into the code right now, such as etorrent_table:tracking_map uses filename instead of parsed torrent structure. Some codes that I don't know could also use filename in certain ways, which parsed structure can't fulfill the same purpose.

Anyway, I'm very new to etorrent code. Please review my first patch.

**Comment by jlouis** [comment]
I see the problem you have with the code. The solution is to slowly hoist the parse_file calls up where applicable to the top-level, and probably use the InfoHash of the torrent as the identifier rather than the File. But you are right it is kind-of a larger change to the code base. With luck, it is possible to hoist the torrent out of the `etorrent_io*` code without too much hassle though.

**Comment by jlouis** [comment]
This one has been solved.
